name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pyinstaller pyperclip

      - name: Build exe
        run: |
          pyinstaller --onefile --console taodanhsach.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: taodanhsach-exe
          path: dist/taodanhsach.exe
